#!/usr/bin/env bash
# Built by Sai Avala

get() {
    if [ -z "$1" ]
        then
            printf "No stock tickers passed.\n"
            return
    fi
    url="http://download.finance.yahoo.com/d/quotes.csv?s=$1&f=l1"
    price=$(curl -s $url)
    ticker=$(printf "%s" "$1" | awk '{print toupper($0)}')
    printf "%s\tprice: %s\n" "$ticker" "$price"
}

add() {
    if [ ! -d ~/.stocks ];then
        mkdir ~/.stocks
    fi
    if [ ! -f ~/.stocks/stocksList.txt ];then
        stock=$(printf "%s" "$1" | awk '{print toupper($0)}')
        printf "%s\n" "$stock" >> ~/.stocks/stocksList.txt
        printf "Added %s to list of stocks.\n" $stock
    else
        ticker=$(echo $1 | awk '{print toupper($0)}')
        if grep -q "$ticker" ~/.stocks/stocksList.txt; then
            echo "Already have $ticker in your watchlist"
        else
            stock=$(printf "%s" "$1" | awk '{print toupper($0)}')
            printf "%s\n" "$stock" >> ~/.stocks/stocksList.txt
            printf "Added %s to list of stocks.\n" $stock
        fi
    fi
}

delete() {
    stock=$(echo $1 | awk '{print toupper($0)}')
    printf "%s" $stock | awk "!/$stock/" ~/.stocks/stocksList.txt > temp && mv temp ~/.stocks/stocksList.txt
    printf "Removed %s\n" "${1}"
}

clean() {
    rm ~/.stocks/stocksList.txt
    rmdir ~/.stocks
}

helper() {
    printf "To add: -add <ticker>, ie. -add xyz \n-clean\n-get xyz\n"
}

list() {
    printf "Stocks in your watchlist\n"
    cat ~/.stocks/stocksList.txt
}

openStockPage() {
    url="https://finance.yahoo.com/q?s=$1"
    open $url
}

if [ -z "$1" ];then
    if [ ! -f ~/.stocks/stocksList.txt ];then
        printf "You must add a stock (i.e. stocks -add xyz)\n"
    else
        stocks=""
        if [ ! -s ~/.stocks/stocksList.txt ];then
            printf "You must add a stock (i.e. stocks -add xyz)\n"
        else
            while read -r line
            do
                stocks+="$line,"
            done < ~/.stocks/stocksList.txt
            # url="http://download.finance.yahoo.com/d/quotes.csv?s=$stocks&f=p"
            url="http://download.finance.yahoo.com/d/quotes.csv?s=$stocks&f=l1a"
            prices=$(curl -s $url)
            prices=(${prices//\n/ })
            stocks=(${stocks//,/ })
            for key in "${!stocks[@]}"; do
                stock=$(echo ${stocks[$key]} | awk '{print toupper($0)}')
                p=${prices[$key]}
                x=(${p//,/ })
                #echo "$stock\tPrice: ${x[0]}\tSomething: ${x[1]}";
                printf "%s\tPrice: %s\n" "${stock}" "${x[0]}"
            done
        fi
    fi
else
    case $1 in
        "-add" )
            add $2;;
        "-get" )
            get $2;;
        "-clean" )
            clean;;
        "-rm" )
            delete $2;;
        "-open" )
            openStockPage $2;;
        "-list" )
            list;;
        "-help" )
            helper;;
    esac
fi
